version: '3'
services:
  stripe-example:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: stripe-example-multi-stage
    ports:
        - '8080:8080'
        - '5005:5005'
        
    environment:
      - ADDITIONAL_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
      - PROFILE=dev
    links:
      - db
  db:
    image: postgres
    ports:
      - '5432:5432'

    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stripe-example
    volumes:
    - ./pgdata:/var/lib/postgresql/data
  